CFLAGS=-g
LDFLAGS=-framework Foundation
OBJECTS=01.plain_objc 02.foundation 03.runtime 04.forwarding 05.categories 06.kvo 07.block 08.block 09.gcd 10.zombies

all: $(OBJECTS)

clean:
	rm -fr $(OBJECTS) *.dSYM

