CFLAGS=-g
LDFLAGS=-framework Foundation
OBJECTS=01.plain_objc 02.foundation 03.runtime 04.forwarding 05.categories 06.kvo 07.block_1 08.block_2 09.block_3 10.gcd_1 11.zombies

all: $(OBJECTS)

clean:
	rm -fr $(OBJECTS) *.dSYM

